//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECW.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Indent = new HashSet<Indent>();
            this.ShoppingCartDetails = new HashSet<ShoppingCartDetails>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Subhead { get; set; }
        public double Price { get; set; }
        public string Orgin { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Taste { get; set; }
        public string Name { get; set; }
        public int Inventory { get; set; }
        public int Sales { get; set; }
        public string Discount { get; set; }
        public bool Condition { get; set; }
        public string No { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indent> Indent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartDetails> ShoppingCartDetails { get; set; }
    }
}
