//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECW.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indent
    {
        public int Id { get; set; }
        public int ShippingAddressId { get; set; }
        public int IndentNumber { get; set; }
        public System.DateTime SubmissionTime { get; set; }
        public string Condition { get; set; }
        public int GoodsId { get; set; }
        public double UnitPrice { get; set; }
        public int GoodsNumber { get; set; }
        public double TotalPrice { get; set; }
        public int UserId { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual ShippingAddress ShippingAddress { get; set; }
        public virtual User User { get; set; }
    }
}
